# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\79383\Documents\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 610)
        MainWindow.setStyleSheet("QMainWindow {background: rgb(56, 56, 56)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.videoWidget = QVideoWidget(self.widget)
        self.videoWidget.setMinimumSize(QtCore.QSize(400, 200))
        self.videoWidget.setStyleSheet("QVideoWidget {background:rgb(30, 30, 30)}")
        self.videoWidget.setObjectName("videoPlayer")
        self.gridLayout_2.addWidget(self.videoWidget, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.widget_3)
        self.playButton.setMinimumSize(QtCore.QSize(34, 30))
        self.playButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.playButton.setStyleSheet(
            " QPushButton {\n"
            "     border: 2px solid #8f8f91;\n"
            "     border-radius: 6px;\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "     min-width: 30px;\n"
            " }\n"
            "\n"
            " QPushButton:pressed {\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            " }"
        )
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.openButton = QtWidgets.QPushButton(self.widget_3)
        self.openButton.setMinimumSize(QtCore.QSize(44, 30))
        self.openButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.openButton.setStyleSheet(
            " QPushButton {\n"
            "     border: 2px solid #8f8f91;\n"
            "     border-radius: 6px;\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "     min-width: 40px;\n"
            " }\n"
            "\n"
            " QPushButton:pressed {\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            " }"
        )
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.controlSlider = QtWidgets.QSlider(self.widget_3)
        self.controlSlider.setMaximumSize(QtCore.QSize(16777215, 32))
        self.controlSlider.setStyleSheet(
            "QSlider::groove:horizontal {\n"
            "     border: 1px solid #999999;\n"
            "     height: 8px; /* по умолчанию бороздка расширяется до размеров ползунка. задав высоту она принимает фиксированный размер */\n"
            "     background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
            "     margin: 2px 0;\n"
            " }\n"
            "\n"
            " QSlider::handle:horizontal {\n"
            "     background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
            "     border: 1px solid #5c5c5c;\n"
            "     width: 18px;\n"
            "     margin: -2px 0; /* рукоятка располагается по умолчанию в прямоугольнике содержимого бороздки. Расширяется наружу от бороздки */\n"
            "     border-radius: 3px;\n"
            " }"
        )
        self.controlSlider.setOrientation(QtCore.Qt.Horizontal)
        self.controlSlider.setObjectName("controlSlider")
        self.horizontalLayout.addWidget(self.controlSlider)
        self.soundSlider = QtWidgets.QSlider(self.widget_3)
        self.soundSlider.setMaximumSize(QtCore.QSize(16777215, 84))
        self.soundSlider.setStyleSheet(
            "QSlider::groove:verticall {\n"
            "     border: 1px solid #999998;\n"
            "     height: 50px; /* по умолчанию бороздка расширяется до размеров ползунка. задав высоту она принимает фиксированный размер */\n"
            "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
            "     margin: 1px;\n"
            " }\n"
            "\n"
            " QSlider::handle:vertical {\n"
            "     background: qlineargradient(x1:0, y1:0, x2:4, y2:4, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
            "     border: 5px solid #5c5c5c;\n"
            "     width: 18px;\n"
            "     margin: -2px 0; /* рукоятка располагается по умолчанию в прямоугольнике содержимого бороздки. Расширяется наружу от бороздки */\n"
            "     border-radius: 2px;\n"
            "    \n"
            " }"
        )
        self.soundSlider.setOrientation(QtCore.Qt.Vertical)
        self.soundSlider.setObjectName("soundSlider")
        self.horizontalLayout.addWidget(self.soundSlider)
        self.speedButton = QtWidgets.QPushButton(self.widget_3)
        self.speedButton.setMinimumSize(QtCore.QSize(44, 30))
        self.speedButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.speedButton.setStyleSheet(
            " QPushButton {\n"
            "     border: 2px solid #8f8f91;\n"
            "     border-radius: 6px;\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "     min-width: 40px;\n"
            " }\n"
            "\n"
            " QPushButton:pressed {\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            " }"
        )
        self.speedButton.setObjectName("speedButton")
        self.horizontalLayout.addWidget(self.speedButton)
        self.gridLayout_2.addWidget(self.widget_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.speedButton.setText(_translate("MainWindow", "1.0"))


from PyQt5.QtMultimediaWidgets import QVideoWidget
